Repository pbdsce/PB_Website, pull requests merged in 2025-07, with the labels that each got.

#348 commented all the CUD apis
  app/(default)/api/achievements-category/route.ts
  app/(default)/api/achievements/route.ts
  app/(default)/api/admin/route.ts
  app/(default)/api/leads/route.ts
  app/(default)/api/leads/upload/route.ts
  app/(default)/api/membersData/route.ts
Labels: Frontend, API

#355 Add docs page
  app/(default)/docs/page.tsx
  components/ui/header.tsx
Labels: Frontend, size-M

#356 Refactor: Remove secret flag logic from PBCTF form and Additional Questions component
  components/forms/pbctfForm.tsx
  components/forms/pbctfForm/AdditionalQuestions.tsx
Labels: Frontend
